# Generated by Django 5.2.16 on 2026-08-07 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('text', models.TextField(blank=True)),
                ('subreddit', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('upvote_ratio', models.FloatField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('permalink', models.URLField()),
                ('search_term', models.CharField(max_length=200)),
                ('created_utc', models.DateTimeField()),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=20, unique=True)),
                ('text', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('permalink', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reddit_data.redditpost')),
            ],
        ),
    ]
